name: "Main"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  build:

    runs-on: "ubuntu-latest"

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: "read"      # to read the repository contents
      pull-requests: "read" # to read pull requests
      pages: "write"        # to deploy to Pages
      id-token: "write"     # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: "github-pages"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
          cache: "pip"

      - run: "pip install -r requirements.txt"

      - uses: "Yeicor/ocp-action@v3.1.3"
        with:
          scripts: "src/main.py"
